### ISSUE TITLE
May I ask if the dataset can be made public

### ISSUE THREAD

**Issue by FuChanglong** [Les1ie/HERI-GCN#1]
May I ask if the dataset can be made public

**Comment by Les1ie** [comment]
包含 1000 条数据的示例可以参考 https://github.com/Les1ie/Wb-MSF 。

完整版的等我做个数据脱敏后再给你😊，最近有亿点点忙😭。

**Comment by Les1ie** [comment]
哈喽，我已经处理好完整版的脱敏数据集啦，下载地址在 [WB-MSF Full dataset](https://github.com/Les1ie/Wb-MSF/releases/tag/v0.1.0)。

如果该数据集对你有帮助，烦请引用下我们的论文，谢谢😊。

**Comment by FuChanglong** [comment]
你好，我正在复现你的论文，但是我做的是微博，推特，aps这三个数据集的转发量的流行度预测，然后我们的是同质图，没有关注关系，然后您的有关注关系，是异构图，请问您有什么建议能够正确复现你的论文吗，因为我看到了您也对比了
CasCN、DeepHawkes、DeepCas这类论文。另外非常感谢您数据集的公开


回家付昌陇20201120513
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Les1ie/HERI-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Les1ie/HERI-GCN] May I ask if the dataset can be made public (Issue #1)





 
哈喽，我已经处理好完整版的脱敏数据集啦，下载地址在 WB-MSF Full dataset。
 
如果该数据集对你有帮助，烦请引用下我们的论文，谢谢😊。

**Comment by Les1ie** [comment]
- 运行的话，代码都在这个仓库里了，只需要配个环境调试一下应该就能跑起来。
- 指标复现的话，得慢慢调参了。整体上超参数比较多，调参的工作量可能会比较大的。

我没有其他更多的建议了，祝你跑出理想的结果、早日中论文😁。

> ps：个人感觉这个方向已经快山穷水尽了，懂得都懂（滑稽。
